project:
  type: website
  output-dir: docs

website:
  title: "Girika’s Data Blog"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
    right:
      - icon: github
        aria-label: GitHub
        href: https://github.com/GirikaChopra

format:
  html:
    theme:
      light: zephyr
      dark: vapor
    css: styles.css
    toc: true
    toc-title: "On this page"
    toc-location: right
    toc-depth: 3
    number-sections: false

