project:
  type: website

website:
  title: "Girika’s Data Blog"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
    right:
      - icon: github
        aria-label: GitHub
        href: https://github.com/ETC5523-2025/assignment-3-creating-a-blog-GirikaChopra

format:
  html:
    theme: cosmo
    css: styles.css




